# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasePack_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BasePack_iOS
  
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage', '~> 4.0'
  pod 'NVActivityIndicatorView'
  pod 'TweeTextField'
  pod 'RealmSwift'
  pod 'FittedSheets', '~> 1.4.6'
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Core'

end
